version: "3"
services:
  node:
    build:
      context: node
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./node:/app
      - ./data:/app/views
    networks:
      - internal

networks:
  internal:
    driver: bridge
