version: "3"
services:
  rtmp-nginx:
    container_name: rtmp-server
    image: docker.io/shakahl/docker-alpine-nginx-rtmp
    ports:
      - "8080:80"
      - "1935:1935"
    networks:
      - internal

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=yourPassword
      - ACCEPT_EULA=Y
    volumes:
      - mssql-data:/var/opt/mssql

  mysql-db:
    container_name: mysql-db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=yourPassword
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - internal
    volumes:
      - ./nginx/confd/:/etc/nginx/conf.d/
      - ./data/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
      - ./nginx/ssl/:/etc/nginx/ssl/

  php:
    image: namoshek/php-mssql:8.1-fpm-alpine
    networks:
      - internal
    volumes:
      - ./data/:/var/www/html/
      - ./logs/:/var/log/

  node:
    build:
      context: node
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./node:/app
      - ./data:/app/views
    networks:
      - internal

  irc:
    image: inspircd/inspircd-docker
    ports:
      - "6667:6667"
      - "6697:6697"
    volumes:
      - ./irc/conf/:/inspircd/conf/
    networks:
      - internal

  teamspeak:
    image: teamspeak
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      TS3SERVER_LICENSE: accept
networks:
  internal:
    driver: bridge

volumes:
  mssql-data:
  mysql-data:
