# Rate limiting zone definition
limit_req_zone $binary_remote_addr zone=mylimit:10m rate=10r/s;

server {
    listen 0.0.0.0:80;
    listen 0.0.0.0:443 default_server ssl;
    listen 0.0.0.0:4433 ssl;  # Port 4433 für Nodered hinzufügen
    listen 0.0.0.0:9443 ssl;  # Port 9443 hinzufügen

    server_name rubizockt.de www.rubizockt.de radio.rubizockt.de;
    root /var/www/html;

    # HTTP security headers
    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options DENY;
    add_header X-XSS-Protection "1; mode=block";
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

    # Location for the main website
    location / {
        limit_req zone=mylimit burst=20 nodelay;
        index index.php index.html;
    }

    # SSL configuration
    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    # PHP handling
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;
    }

    # Cache static files
    location ~* \.(jpg|jpeg|gif|css|png|js|ico|html)$ {
        expires max;
        log_not_found off;
    }

    # Block access to sensitive paths (e.g., boaform exploit attempts)
    location ~* /boaform/ {
        return 403;
    }

    # Stricter rate limiting for login pages
    location /login {
        limit_req zone=mylimit burst=5 nodelay;
        try_files $uri /index.php?$query_string;
    }

    # Location for Shoutcast stream with CORS enabled
    location /stream {
        add_header 'Access-Control-Allow-Origin' '*';
        proxy_pass http://82.145.63.6:5739/stream;
        proxy_set_header Host $host;
    }
    
    # Block specific IPs with suspicious behavior
    deny 154.213.184.25;
    deny 103.208.233.99;
    deny 185.224.128.59;
}
